### ISSUE TITLE
Adding Metadata Support to the Message Encoding Binding Element

### ISSUE THREAD

**Issue by JMLOSP** [dotnet/docs.es-es#101]
There's a typo in Adding Metadata Support to the Message Encoding Binding Element area text TextMessageEncodingBinidngElement should be TextMessageEncodingBindingElement 

Thanks.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ec24f4ae-ebea-dd11-d149-e20ba10ea101
* Version Independent ID: 7c175ff3-d413-4144-bd73-da88f07bf14f
* Content: [Codificador de mensaje personalizado: Codificador de texto personalizado](https://docs.microsoft.com/es-es/dotnet/framework/wcf/samples/custom-message-encoder-custom-text-encoder)
* Content Source: [docs/framework/wcf/samples/custom-message-encoder-custom-text-encoder.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/wcf/samples/custom-message-encoder-custom-text-encoder.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #10679](https://github.com/dotnet/docs/issues/10679) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @JMLOSP 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/10679

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
