### ISSUE TITLE
No C++ Doc

### ISSUE THREAD

**Issue by petacreepers23** [dotnet/docs.es-es#124]
Developing for UWP with C++, this kind of error occur, and there is no Documentation at all

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: be7944fe-6db1-0fe4-7a89-29f5594b2674
* Version Independent ID: 152ac482-0811-0869-addd-258b689fbe3f
* Content: [Filtrar Realizar llamadas seguras para subprocesos a controles de formularios Windows Forms](https://docs.microsoft.com/es-es/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls#feedback)
* Content Source: [docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11841](https://github.com/dotnet/docs/issues/11841) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @petacreepers23 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11841

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
