### ISSUE TITLE
the code of the second example is incorrect,

### ISSUE THREAD

**Issue by hmuschett** [dotnet/docs.es-es#80]
the code of the second example is incorrect, it has the same sentence as the first code

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 433a56c8-1c93-32fb-eb1d-8395a9760c65
* Version Independent ID: e3f35410-f243-4309-1436-89ade7a34d19
* Content: [Objetos: Guía de programación de C#](https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/classes-and-structs/objects)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/objects.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/programming-guide/classes-and-structs/objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by hmuschett** [comment]
el codigo del segundo ejemplo hace tiene  el mismo codigo que el el primero solo le cambian el nombre a los objetos. al final el comportamiento es el mismo

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #10258](https://github.com/dotnet/docs/issues/10258) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @hmuschett 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/10258.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
